const MenNecklacesData = {
    Necklaces: [
    {
        _id: '1',
        name: 'Peora Men Necklace' ,
        catagory: 'Necklace',
        image:'/Men/Accessories/Necklaces/wn1.jpg' ,
        price: 130,
        brand: 'Peora',
        rating: 4.4,
        numReviews: 8,
        description: "Necklace for Peora.",
        countInStock: 4,
    },
    {
        _id: '2',
        name: 'Peora Men Necklace' ,
        catagory: 'Necklace',
        image:'/Men/Accessories/Necklaces/wn2.jpg' ,
        price: 290,
        brand: 'Peora',
        rating: 4,
        numReviews: 80,
        description: "Necklace for Men by Peora..",
        countInStock: 4,
        },
        {
            _id: '3',
            name: 'Peora Men Necklace' ,
            catagory: 'Necklace',
            image:'/Men/Accessories/Necklaces/wn3.jpg' ,
            price: 180,
            brand: 'Peora',
            rating: 5,
            numReviews: 89,
            description: "Necklace for Men by Peora.",
            countInStock: 4,
            },
            {
             _id: '4',
             name: 'Sukkhi Men Necklace' ,
            catagory: 'Necklace',
            image: '/Men/Accessories/Necklaces/wn4.jpg',
            price: 100,
            brand: 'Sukkhi',
            rating: 4.5,
            numReviews: 17,
            description: "Necklace Men by Sukkhi.",
            countInStock: 10,
                },
                {
                    _id: '5',
                    name: 'Sukkhi Men Necklace' ,
            catagory: 'Necklace',
            image: '/Men/Accessories/Necklaces/wn5.jpg',
            price: 200,
            brand: 'Sukkhi',
            rating: 5,
            numReviews: 9,
            description: "Necklace Men by Sukkhi.",
            countInStock: 16,
                    },
],

}

export default  MenNecklacesData;