import React from 'react';
const MenShortsData = {
    Shorts: [

    {
        _id: '1',
        name: 'U.S Polo Assn. Men Short' ,
        catagory: 'Short',
        image:'/Men/Buttonwear/Shorts/mso1.jpg' ,
        price: 500,
        brand: 'U.S Polo Assn.',
        rating: 3,
        numReviews: 8,
        description: "Short for Men by U.S Polo Assn..",
        countInStock: 4,
    },
    {
        _id: '2',
        name: 'U.S Polo Assn. Men Short' ,
        catagory: 'Short',
        image:'/Men/Buttonwear/Shorts/mso2.jpg' ,
        price: 200,
        brand: 'U.S Polo Assn.',
        rating: 5,
        numReviews: 80,
        description: "Short for Men by U.S Polo Assn..",
        countInStock: 4,
        },
        {
            _id: '3',
            name: 'U.S Polo Assn. Men Short' ,
            catagory: 'Short',
            image:'/Men/Buttonwear/Shorts/mso3.jpg' ,
            price: 400,
            brand: 'U.S Polo Assn.',
            rating: 5,
            numReviews: 89,
            description: "Short for Men by U.S Polo Assn..",
            countInStock: 4,
            },
            {
             _id: '4',
             name: 'Levis Men Short' ,
            catagory: 'Short',
            image: '/Men/Buttonwear/Shorts/mso4.jpg',
            price: 860,
            brand: 'Levis',
            rating: 4.5,
            numReviews: 17,
            description: "Short Men by Levis.",
            countInStock: 10,
                },
                {
                    _id: '5',
                    name: 'Levis Men Short' ,
            catagory: 'Short',
            image: '/Men/Buttonwear/Shorts/mso5.jpg',
            price: 200,
            brand: 'Levis',
            rating: 5,
            numReviews: 89,
            description: "Short Men by Levis.",
            countInStock: 10,
                    },
                    {
                        _id: '6',
                         name: 'Levis Men Short' ,
            catagory: 'Short',
            image: '/Men/Buttonwear/Shorts/mso6.jpg',
            price: 500,
            brand: 'levis',
            rating: 5,
            numReviews: 70,
            description: "Short Men by Levis.",
            countInStock: 10,
     },
     {
        _id: '7',
        name: 'Levis Men Short' ,
            catagory: 'Short',
            image: '/Men/Buttonwear/Shorts/mso7.jpg',
            price: 330,
            brand: 'Levis',
            rating: 2.5,
            numReviews: 19,
            description: "Jean Men by Levis.",
            countInStock: 100,
},
],

}

export default  MenShortsData;