const MenTshirtsData = {
    Tshirt: [

    {
    _id: '1',
    name: 'Levis Men T-shirt' ,
    catagory: 'T-shirt',
    image: '/Men/Topwear/Tshirts/mt1.jpg',
    price: 400,
    brand: 'Levis',
    rating: 5,
    numReviews: 18,
    description: "T-shirt for Men by Levis.",
    countInStock: 4,

    },
    {
        _id: '2',
        name: 'Levis Men T-shirt' ,
        catagory: 'T-shirt',
        image: '/Men/Topwear/Tshirts/mt2.jpg',
        price: 500,
        brand: 'Levis',
        rating: 4.5,
        numReviews: 17,
        description: "T-shirt for Men by Levis.",
        countInStock: 7,
    
        },
        {
            _id: '3',
            name: 'Levis Men T-shirt' ,
            catagory: 'T-shirt',
            image:'/Men/Topwear/Tshirts/mt3.jpg',
            price: 900,
            brand: 'Levis',
            rating: 4,
            numReviews: 16,
            description: "T-shirt for women by Levis.",
            countInStock: 4,
        
            },
            {
                _id: '4',
                name: 'Puma Men T-shirt' ,
                catagory: 'T-shirt',
                image:'/Men/Topwear/Tshirts/mt4.jpg' ,
                price: 1000,
                brand: 'Puma',
                rating: 5,
                numReviews: 20,
                description: "T-shirt for Men by Levis.",
                countInStock: 10,
                },
                {
                    _id: '5',
                    name: 'Puma Men T-shirt' ,
                    catagory: 'T-shirt',
                    image:'/Men/Topwear/Tshirts/mt5.jpg',
                    price: 2000,
                    brand: 'Puma',
                    rating: 4.5,
                    numReviews: 71,
                    description: "T-shirt for Men by Levis.",
                    countInStock: 11,
                    },
                    {
                        _id: '6',
                        name: 'Puma Men T-shirt' ,
                        catagory: 'T-shirt',
                        image:'/Men/Topwear/Tshirts/mt6.jpg' ,
                        price: 750,
                        brand: 'Puma',
                        rating: 4,
                        numReviews: 8,
                        description: "T-shirt for Men by Levis.",
                        countInStock: 4,
     },
     {
        _id: '7',
        name: 'U.S Polo Assn. Men T-shirt' ,
        catagory: 'T-shirt',
        image:'/Men/Topwear/Tshirts/mt7.jpg' ,
        price: 1350,
        brand: 'U.S Polo Assn.',
        rating: 4,
        numReviews: 8,
        description: "T-shirt for Men by U.S Polo Assn..",
        countInStock: 4,
},
],

}

export default MenTshirtsData;