const MenJacketsData = {
    Jackets: [

    {
   _id: '1',
    name: 'Puma Men Jacket' ,
    catagory: 'Jacket',
    image: '/Men/Topwear/Jackets/mj1.jpg',
    price: 700,
    brand: 'Puma',
    rating: 2.5,
    numReviews: 120,
    description: "Jacket for Men by Puma.",
    countInStock: 200,

    },
    {
       _id: '2',
        name: 'Levis Men Jacket' ,
        catagory: 'Jacket',
        image: '/Men/Topwear/Jackets/mj2.jpg',
        price: 9000,
        brand: 'Levis',
        rating: 4.5,
        numReviews: 17,
        description: "Jacket for Men by Levis.",
        countInStock: 10,
        },
        {
           _id: '3',
            name: 'Levis Men Jacket' ,
            catagory: 'Jacket',
            image:'/Men/Topwear/Jackets/mj3.jpg',
            price: 900,
            brand: 'Levis',
            rating: 4,
            numReviews: 16,
            description: "Jacket for woMen by Levis.",
            countInStock: 4,
            },
            {
               _id: '4',
                name: 'Reebook Men Jacket' ,
                catagory: 'Jacket',
                image:'/Men/Topwear/Jackets/mj4.jpg' ,
                price: 10000,
                brand: 'Reebook',
                rating: 4,
                numReviews: 200,
                description: "Jacket for Men by Reebook.",
                countInStock: 10,
                },
                {
                   _id: '5',
                    name: 'Levis Men Jacket' ,
                    catagory: 'Jacket',
                    image:'/Men/Topwear/Jackets/mj5.jpg',
                    price: 2000,
                    brand: 'Levis',
                    rating: 4.5,
                    numReviews: 900,
                    description: "Jacket for Men by Levis.",
                    countInStock: 110,
                    },
                    {
                       _id: '6',
                        name: 'Levis Men Jacket' ,
                        catagory: 'Jacket',
                        image:'/Men/Topwear/Jackets/mj6.jpg' ,
                        price: 750,
                        brand: 'Levis',
                        rating: 4,
                        numReviews: 80,
                        description: "Jacket for Men by Levis.",
                        countInStock: 90,
     },
     {
       _id: '7',
        name: 'Reebook Men Jacket' ,
        catagory: 'Jacket',
        image:'/Men/Topwear/Jackets/mj7.jpg' ,
        price: 1350,
        brand: 'Reebook.',
        rating: 4.5,
        numReviews: 8,
        description: "Jacket for Men by Reebook",
        countInStock: 4,
},
],

}

export default MenJacketsData;