const MenTrousersData = {
    Trousers: [

    {
        _id: '1',
        name: 'U.S Polo Assn. Men Trouser' ,
        catagory: 'Trouser',
        image:'/Men/Buttonwear/Trousers/mtr1.jpg' ,
        price: 1500,
        brand: 'U.S Polo Assn.',
        rating: 3,
        numReviews: 8,
        description: "Trouser for Men by U.S Polo Assn..",
        countInStock: 4,
    },
    {
        _id: '2',
        name: 'U.S Polo Assn. Men Trouser' ,
        catagory: 'Trouser',
        image:'/Men/Buttonwear/Trousers/mtr2.jpg' ,
        price: 2000,
        brand: 'U.S Polo Assn.',
        rating: 5,
        numReviews: 80,
        description: "Trouser for Men by U.S Polo Assn..",
        countInStock: 4,
        },
        {
            _id: '3',
            name: 'U.S Polo Assn. Men Trouser' ,
            catagory: 'Trouser',
            image:'/Men/Buttonwear/Trousers/mtr3.jpg' ,
            price: 4000,
            brand: 'U.S Polo Assn.',
            rating: 5,
            numReviews: 89,
            description: "Trouser for Men by U.S Polo Assn..",
            countInStock: 4,
            },
            {
             _id: '4',
             name: 'Puma Men Trouser' ,
            catagory: 'Trouser',
            image: '/Men/Buttonwear/Trousers/mtr4.jpg',
            price: 2000,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 17,
            description: "Puma Men by Levis.",
            countInStock: 10,
                },
                {
                    _id: '5',
                    name: 'Levis Men Trouser' ,
            catagory: 'Trouser',
            image: '/Men/Buttonwear/Trousers/mtr5.jpg',
            price: 800,
            brand: 'Levis',
            rating: 3,
            numReviews: 922,
            description: "Trouser Men by Levis.",
            countInStock: 10,
                    },
                    {
                        _id: '6',
                         name: 'Levis Men Trouser' ,
            catagory: 'Trouser',
            image: '/Men/Buttonwear/Trousers/mtr6.jpg',
            price: 600,
            brand: 'Levis',
            rating: 5,
            numReviews: 70,
            description: "Trouser Men by Levis.",
            countInStock: 10,
     },
     {
        _id: '7',
        name: 'Levis Men Trouser' ,
            catagory: 'Trouser',
            image: '/Men/Buttonwear/Trousers/mtr7.jpg',
            price: 1000,
            brand: 'Levis',
            rating: 5,
            numReviews: 19,
            description: "Trouser Men by Levis.",
            countInStock: 100,
},
],

}

export default  MenTrousersData;