const Data = {
    Products:[
        {
            _id:'1',
            name:'Nike Slim Shirts',
            Categories:'Shirts',
            image:"/images/ms1.jpg",
            price: 1300,
            brand:'Nike',
            rating: 4.5,
            numReviews:106,
            description:'High Quality Product',
            countInStock: 0,
        },
         {
            _id:'2',
            name:'Nike Shirts',
            Categories:'Shirts',
            image:"/images/ms2.jpg",
            price: 90,
            brand:'Nike',
            rating: 4.5,
            numReviews:10,
            description:'High Quality Product',
            countInStock: 5,
        },
         {
            _id:'3',
            name:'Nike Slim Shirts',
            Categories:'Shirts',
            image:"/images/ms3.jpg",
            price: 130,
            brand:'Nike',
            rating: 4.5,
            numReviews:10,
            description:'High Quality Product',
            countInStock: 5,
        },
         {
            _id:'4',
            name:'Nike Slim Shirts',
            Categories:'Shirts',
            image:"/images/ms4.jpg",
            price: 130,
            brand:'Nike',
            rating: 4.5,
            numReviews:10,
            description:'High Quality Product',
            countInStock: 5,
        },
         {
            _id:'5',
            name:'Nike Slim Shirts',
            Categories:'Shirts',
            image:"/images/ms5.jpg",
            price: 130,
            brand:'Nike',
            rating: 5,
            numReviews:10,
            description:'High Quality Product',
            countInStock: 5,
        }
    ]
}
export default Data;