const MenShirtsData = {
    Shirt: [

    {
    _id: '1',
    name: 'Puma Men Shirt' ,
    catagory: 'Shirt',
    image: '/Men/Topwear/Shirts/ms1.jpg',
    price: 700,
    brand: 'Puma',
    rating: 3.5,
    numReviews: 120,
    description: "Shirt for Men by Puma.",
    countInStock: 200,

    },
    {
        _id: '2',
        name: 'Levis Men Shirt' ,
        catagory: 'Shirt',
        image: '/Men/Topwear/Shirts/ms2.jpg',
        price: 900,
        brand: 'Levis',
        rating: 4.5,
        numReviews: 17,
        description: "Shirt for Men by Levis.",
        countInStock: 100,
        },
        {
            _id: '3',
            name: 'Levis Men Shirt' ,
            catagory: 'Shirt',
            image:'/Men/Topwear/Shirts/ms3.jpg',
            price: 900,
            brand: 'Levis',
            rating: 4,
            numReviews: 16,
            description: "Shirt for women by Levis.",
            countInStock: 4,
            },
            {
                _id: '4',
                name: 'Levis Men Shirt' ,
                catagory: 'Shirt',
                image:'/Men/Topwear/Shirts/ms4.jpg' ,
                price: 1000,
                brand: 'Puma',
                rating: 5,
                numReviews: 20,
                description: "Shirt for Men by Levis.",
                countInStock: 10,
                },
                {
                    _id: '5',
                    name: 'Levis Men Shirt' ,
                    catagory: 'Shirt',
                    image:'/Men/Topwear/Shirts/ms5.jpg',
                    price: 2000,
                    brand: 'Puma',
                    rating: 4.5,
                    numReviews: 90,
                    description: "Shirt for Men by Levis.",
                    countInStock: 110,
                    },
                    {
                        _id: '6',
                        name: 'Levis Men Shirt' ,
                        catagory: 'Shirt',
                        image:'/Men/Topwear/Shirts/ms6.jpg' ,
                        price: 750,
                        brand: 'Puma',
                        rating: 4,
                        numReviews: 80,
                        description: "Shirt for Men by Levis.",
                        countInStock: 90,
     },
      {
        _id: '7',
        name: 'U.S Polo Assn. Men Shirt' ,
        catagory: 'Shirt',
        image:'/Men/Topwear/Shirts/ms7.jpg' ,
        price: 1350,
        brand: 'U.S Polo Assn.',
        rating: 4,
        numReviews: 8,
        description: "Shirt for Men by U.S Polo Assn.",
        countInStock: 0,
},
]

}

export default MenShirtsData;