const MenJeansData = {
    Jeans: [

    {
        _id: '1',
        name: 'U.S Polo Assn. Men Jean' ,
        catagory: 'Jean',
        image:'/Men/Buttonwear/Jeans/mje1.jpg' ,
        price: 1500,
        brand: 'U.S Polo Assn.',
        rating: 3,
        numReviews: 8,
        description: "Jean for Men by U.S Polo Assn..",
        countInStock: 4,
    },
    {
        _id: '2',
        name: 'U.S Polo Assn. Men Jean' ,
        catagory: 'Jean',
        image:'/Men/Buttonwear/Jeans/mje2.jpg' ,
        price: 2000,
        brand: 'U.S Polo Assn.',
        rating: 5,
        numReviews: 80,
        description: "Jean for Men by U.S Polo Assn..",
        countInStock: 4,
        },
        {
            _id: '3',
            name: 'U.S Polo Assn. Men Jean' ,
            catagory: 'Jean',
            image:'/Men/Buttonwear/Jeans/mje3.jpg' ,
            price: 4000,
            brand: 'U.S Polo Assn.',
            rating: 5,
            numReviews: 89,
            description: "Jean for Men by U.S Polo Assn..",
            countInStock: 4,
            },
            {
             _id: '4',
             name: 'Levis Men Jean' ,
            catagory: 'Jean',
            image: '/Men/Buttonwear/Jeans/mje4.jpg',
            price: 9000,
            brand: 'Levis',
            rating: 4.5,
            numReviews: 17,
            description: "Jean Men by Levis.",
            countInStock: 10,
                },
                {
                    _id: '5',
                    name: 'Levis Men Jean' ,
            catagory: 'Jean',
            image: '/Men/Buttonwear/Jeans/mje5.jpg',
            price: 2000,
            brand: 'Levis',
            rating: 5,
            numReviews: 89,
            description: "Jean Men by Levis.",
            countInStock: 10,
                    },
                    {
                        _id: '6',
                         name: 'Levis Men Jean' ,
            catagory: 'Jean',
            image: '/Men/Buttonwear/Jeans/mje6.jpg',
            price: 700,
            brand: 'Levis',
            rating: 5,
            numReviews: 70,
            description: "Jean Men by Levis.",
            countInStock: 10,
     },
     {
        _id: '7',
        name: 'Levis Men Jean' ,
            catagory: 'Jean',
            image: '/Men/Buttonwear/Jeans/mje7.jpg',
            price: 8000,
            brand: 'Levis',
            rating: 2.5,
            numReviews: 19,
            description: "Jean Men by Levis.",
            countInStock: 100,
},
],

}

export default  MenJeansData;