const MenSlippersData = {
    Slippers: [

    {
        _id: '1',
        name: 'U.S Polo Assn. Men Slipper' ,
        catagory: 'Slipper',
        image:'/Men/Footwear/Slippers/wsl1.jpg' ,
        price: 2500,
        brand: 'U.S Polo Assn.',
        rating: 5,
        numReviews: 118,
        description: "Slipper for Men by U.S Polo Assn..",
        countInStock: 4,
    },
    {
        _id: '2',
         name: 'Puma Men Slipper' ,
            catagory: 'Slipper',
            image:'/Men/Footwear/Slippers/wsl2.jpg' ,
            price: 4000,
            brand: 'Puma',
            rating: 5,
            numReviews: 809,
            description: "Slipper for Men by Puma.",
            countInStock: 4,
        },
        {
            _id: '3',
            name: 'Levis Men Slipper' ,
            catagory: 'Slipper',
            image: '/Men/Footwear/Slippers/wsl3.jpg',
            price: 900,
            brand: 'Levis',
            rating: 4.5,
            numReviews: 17,
            description: "Slipper Men by Levis.",
            countInStock: 10,
            },
            {
             _id: '4',
             name: 'Levis Men Slipper' ,
            catagory: 'Slipper',
            image: '/Men/Footwear/Slippers/wsl4.jpg',
            price:8000,
            brand: 'Levis',
            rating: 4.5,
            numReviews: 17,
            description: "Slipper Men by Levis.",
            countInStock: 10,
                },
                {
                    _id: '5',
                    name: 'Puma Men Slipper' ,
            catagory: 'Slipper',
            image:'/Men/Footwear/Slippers/wsl5.jpg' ,
            price: 4000,
            brand: 'Puma',
            rating: 5,
            numReviews: 809,
            description: "Slipper for Men by Puma.",
            countInStock: 4,
                    },
                    {
                        _id: '6',
                         name: 'Levis Men Slipper' ,
            catagory: 'Slipper',
            image: '/Men/Footwear/Slippers/wsl6.jpg',
            price: 700,
            brand: 'Levis',
            rating: 5,
            numReviews: 70,
            description: "Slipper Men by Levis.",
            countInStock: 10,
     },
],

}

export default  MenSlippersData;