const MenShoesData = {
    Shoes: [

    {
        _id: '1',
        name: 'Puma Men Shoes' ,
        catagory: 'Shoes',
        image:'/Men/Footwear/Shoes/wso1.jpg' ,
        price: 1900,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 689,
        description: "Shoes for Men by Puma.",
        countInStock: 4,
    },
    {
        _id: '2',
        name: 'Puma Men Shoes' ,
        catagory: 'Shoes',
        image:'/Men/Footwear/Shoes/wso2.jpg' ,
        price: 8000,
        brand: 'Puma',
        rating: 5,
        numReviews: 800,
        description: "Shoes for Men by Puma.",
        countInStock: 4,
        },
        {
            _id: '3',
            name: 'Puma Men Shoes' ,
            catagory: 'Shoes',
            image:'/Men/Footwear/Shoes/wso3.jpg' ,
            price: 4000,
            brand: 'Puma',
            rating: 5,
            numReviews: 89,
            description: "Shoes for Men by Puma.",
            countInStock: 4,
            },
            {
             _id: '4',
             name: 'Levis Men Shoes' ,
            catagory: 'Shoes',
            image: '/Men/Footwear/Shoes/wso4.jpg',
            price: 900,
            brand: 'Levis',
            rating: 4.5,
            numReviews: 17,
            description: "Shoes Men by Levis.",
            countInStock: 10,
                },
                {
                    _id: '5',
                    name: 'Levis Men Shoes' ,
            catagory: 'Shoes',
            image: '/Men/Footwear/Shoes/wso5.jpg',
            price: 8000,
            brand: 'Levis',
            rating: 5,
            numReviews: 89,
            description: "Shoes Men by Levis.",
            countInStock: 10,
                    },
                    {
                        _id: '6',
                         name: 'Levis Men Shoes' ,
            catagory: 'Shoes',
            image: '/Men/Footwear/Shoes/wso6.jpg',
            price: 7000,
            brand: 'Levis',
            rating: 5,
            numReviews: 70,
            description: "Shoes Men by Levis.",
            countInStock: 10,
     },
     {
                        _id: '7',
                         name: 'Levis Men Shoes' ,
            catagory: 'Shoes',
            image: '/Men/Footwear/Shoes/wso7.jpg',
            price: 7000,
            brand: 'Levis',
            rating: 5,
            numReviews: 70,
            description: "Shoes Men by Levis.",
            countInStock: 10,
     },
     {
        _id: '8',
       name: 'Puma Men Shoes' ,
            catagory: 'Shoes',
            image:'/Men/Footwear/Shoes/wso8.jpg' ,
            price: 4000,
            brand: 'Puma',
            rating: 5,
            numReviews: 89,
            description: "Shoes for Men by Puma.",
            countInStock: 4,
},
],

}

export default  MenShoesData;